# Generated by Django 3.1.6 on 2021-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210326_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('slug', models.SlugField(max_length=40)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
